-- Expects create_tables.sql was run earlier
---
-- Change from Single column PK to CPK
-- Drop single column PK
ALTER TABLE orders DROP CONSTRAINT orders_pkey;

-- Create CPK
ALTER TABLE orders
ADD CONSTRAINT orders_cpk
PRIMARY KEY (supplier_id, id);


-- Alternative:
-- Convert "customers" from single PK to CPK
ALTER TABLE customers DROP CONSTRAINT customers_pkey CASCADE;
ALTER TABLE customers
ADD CONSTRAINT customers_cpk
PRIMARY KEY (supplier_id, id);

-- Create multi-column primary key and foreign key
DROP TABLE IF EXISTS orders_with_cpk;
CREATE TABLE orders_with_cpk (
  id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  supplier_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  quantity INTEGER NOT NULL,
  CONSTRAINT orders_pkey_cpk
    PRIMARY KEY (supplier_id, id),
  CONSTRAINT fk_customer
      FOREIGN KEY (supplier_id, id)
      REFERENCES customers (supplier_id, id)
);

-- Insert orders_with_cpk
INSERT INTO orders_with_cpk (supplier_id, customer_id, quantity)
SELECT
  s.id,                                        -- Random supplier_id from suppliers table
  (10 + random() * 50)::int AS customer_id,            -- Random customer_id
  (1 + random() * 10)::int AS quantity                  -- Random quantity
FROM generate_series(1, 100000) AS g                       -- Generate 100 rows
CROSS JOIN LATERAL (SELECT id FROM suppliers ORDER BY random() LIMIT 1) AS s;

-- Normally we'd share a single sequence across all tenants
-- What if we wanted unique sequences per tenant?
--
-- Create Sequences
CREATE SEQUENCE IF NOT EXISTS supplier_1_seq;
CREATE SEQUENCE IF NOT EXISTS supplier_2_seq;
CREATE SEQUENCE IF NOT EXISTS supplier_3_seq;

DROP TABLE IF EXISTS orders_with_seq;
CREATE TABLE IF NOT EXISTS orders_with_seq (
  -- id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  supplier_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  quantity INTEGER NOT NULL,
  CONSTRAINT orders_with_seq_pkey_cpk
  PRIMARY KEY (supplier_id, id)
);


-- Could manually specify sequence to use for inserts
-- assuming sequences were created in advance, and matched
-- to suppliers
INSERT INTO orders_with_seq (id, supplier_id, customer_id, quantity)
VALUES (nextval('supplier_1_seq'), 1, 1, 1);

INSERT INTO orders_with_seq (id, supplier_id, customer_id, quantity)
VALUES (nextval('supplier_2_seq'), 2, 1, 1);

INSERT INTO orders_with_seq (id, supplier_id, customer_id, quantity)
VALUES (nextval('supplier_3_seq'), 3, 1, 1);
